platform :ios,'8.0'

target 'MAMapDemo' do
#pod 'AMap3DMap-NO-IDFA', '~> 5.0.0'
pod 'AMapSearch-NO-IDFA', '~> 5.0.0'
pod 'AMapLocation-NO-IDFA'
pod 'AMapNavi-NO-IDFA', '~> 5.0.0'


pod 'SDWebImage', '~> 4.0.0'
end
