use_frameworks!

workspace  ‘SwiftDemo.xcworkspace’

platform:ios,’8.0’

target ‘SwiftDemo’ do
    project ‘SwiftDemo.xcodeproj’

end

target ’SwiftTarget’ do
    project ‘SwiftTarget.xcodeproj’

    pod 'AFNetworking', '~> 3.1.0'

    pod 'Alamofire', '~> 4.4'

end
