platform :ios,'8.0'
target 'JMCDemo' do
pod 'Bugly', '2.4.7'
pod 'MJRefresh', '3.1.12'
pod 'MJExtension', '3.0.13'
pod 'FMDB', '2.6.2'
pod 'Masonry', '1.0.2'
pod 'JSONModel', '1.7.0'
pod 'SDCycleScrollView', '1.65'
pod 'SDAutoLayout', '2.1.7'
pod 'AFNetworking', '3.1.0'
pod 'YYKit', '1.0.9'
pod 'TPKeyboardAvoiding', '1.3.1'
pod 'HMSegmentedControl', '1.5.3'
pod 'BTLabel', '1.0.1'
pod 'GCPlaceholderTextView', '1.0.1'
pod 'LCCoolHUD', '1.0.3'
pod 'KeychainItemWrapper', '1.2'
pod 'Reachability', '3.2'
pod 'VPImageCropper', '0.0.4'


pod 'BaiduMapKit', '3.2.1'
pod 'JPush', '2.1.9'
pod 'WXSDKCoreKit', '1.7.5'


pod 'JKDBModel-JDBR', '0.0.1'
pod 'XHPopMenu', '1.0.9'




end
